CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS flowersblog_posts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    flower_name VARCHAR(255) NOT NULL,
    color VARCHAR(100) NOT NULL,
    season VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    COLUMN image_url VARCHAR(255);
);

